# 混匀动作
string sn                  # 设备 SN 号
int32 volume               # 体积（0.01uL 单位）
int32 speed                # 速度（1-10）
int32 times                # 次数
---
bool success               # 是否成功
string response            # 响应内容
string result_sn           # 设备 SN 号
builtin_interfaces/Time result_timestamp  # 时间戳
---
int32 current_times        # 当前已完成次数（反馈）
